version: '3.3'

services:
  web:
    image: vblinden/vblinden
    ports:
      - 5100:80
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.vblinden-http.entrypoints=http"
        - "traefik.http.routers.vblinden-http.rule=Host(`vblinden.nl`) || Host(`www.vblinden.nl`)"
        - "traefik.http.middlewares.vblinden-redirect.redirectregex.regex=^http://(?:www.)?vblinden.nl/(.*)"
        - "traefik.http.middlewares.vblinden-redirect.redirectregex.replacement=https://www.vblinden.nl/$${1}"
        - "traefik.http.routers.vblinden-http.middlewares=vblinden-redirect"
        - "traefik.http.routers.vblinden-http.middlewares=https-redirect"
        - "traefik.http.routers.vblinden-https.rule=Host(`vblinden.nl`) || Host(`www.vblinden.nl`)"
        - "traefik.http.middlewares.vblinden-redirect-https.redirectregex.regex=^https://vblinden.nl/(.*)"
        - "traefik.http.middlewares.vblinden-redirect-https.redirectregex.replacement=https://www.vblinden.nl/$${1}"
        - "traefik.http.routers.vblinden-https.middlewares=vblinden-redirect-https"
        - "traefik.http.routers.vblinden-https.entrypoints=https"
        - "traefik.http.routers.vblinden-https.tls=true"
        - "traefik.http.routers.vblinden-https.tls.certresolver=le"
        - "traefik.http.services.vblinden.loadbalancer.server.port=80"
        - "traefik.http.middlewares.vblinden-redirect.redirectregex.permanent=true"
        - "traefik.http.middlewares.vblinden-redirect-https.redirectregex.permanent=true"

networks:
  traefik-public:
    external: true
